import React, { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Alert, Linking, Platform, Pressable, SafeAreaView, ScrollView, StatusBar, StyleSheet, Text, View } from 'react-native';
import { WebView } from 'react-native-webview';
import * as Haptics from 'expo-haptics';
import * as Notifications from 'expo-notifications';
import * as WebBrowser from 'expo-web-browser';
import Constants from 'expo-constants';

const SITE = Constants.expoConfig?.extra?.siteUrl || 'https://ciboshop.eu';
const C = { cream:'#F7F0E3', paper:'#FFFDF8', green:'#0F2B24', green2:'#176E63', orange:'#F47721', gold:'#B78C3C', ink:'#18201D', muted:'#7A776E', border:'#E3D4BA', soft:'#EFE4D1' };

Notifications.setNotificationHandler({ handleNotification: async () => ({ shouldShowBanner:true, shouldShowList:true, shouldPlaySound:true, shouldSetBadge:false }) });

function BrandMark(){return <View style={styles.brandWrap}><View style={styles.oven}><Text style={styles.flame}>🔥</Text></View><Text style={styles.brand}>CIBO DI STRADA</Text><Text style={styles.subbrand}>TRUE NEAPOLITAN PIZZA</Text></View>}
function QuickCard({emoji,title,subtitle,onPress,accent}){return <Pressable onPress={onPress} style={({pressed})=>[styles.quickCard,{borderColor:accent||C.border},pressed&&{transform:[{scale:.985}],opacity:.92}]}><Text style={styles.quickEmoji}>{emoji}</Text><View style={{flex:1}}><Text style={styles.quickTitle}>{title}</Text><Text style={styles.quickSub}>{subtitle}</Text></View><Text style={styles.chev}>›</Text></Pressable>}

function Home({openPage}){
 const enablePush=async()=>{try{const current=await Notifications.getPermissionsAsync();let status=current.status;if(status!=='granted'){status=(await Notifications.requestPermissionsAsync()).status}if(status!=='granted'){Alert.alert('Известията са изключени','Можеш да ги разрешиш по-късно от настройките на телефона.');return}await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);Alert.alert('Готово','CIBO може да ти показва известия за поръчки и оферти.')}catch{Alert.alert('Неуспешно','Разрешението за известия не можа да бъде активирано.')}};
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.home}><BrandMark/><View style={styles.hero}><Text style={styles.kicker}>ЗЛАТОГРАД • ITALIAN STREET FOOD</Text><Text style={styles.heroTitle}>Любимата храна.{'\n'}Само на един клик.</Text><Text style={styles.heroText}>Поръчай директно от CIBO. Карта, Apple Pay и Google Pay се обработват през защитения платежен поток на сайта.</Text><Pressable style={styles.primary} onPress={()=>openPage('Поръчай',SITE)}><Text style={styles.primaryText}>ПОРЪЧАЙ СЕГА</Text></Pressable></View><Text style={styles.sectionTitle}>CIBO НА ЕДНО МЯСТО</Text><QuickCard emoji="🍕" title="Меню" subtitle="Пици, бургери, hot box, картофки и напитки" accent={C.orange} onPress={()=>openPage('Меню',SITE)}/><QuickCard emoji="★" title="CIBO CLUB" subtitle="Провери награда и специални предложения" accent={C.green2} onPress={()=>openPage('CIBO CLUB',SITE)}/><QuickCard emoji="🎮" title="CIBO KIDS" subtitle="Забавление за най-малките CIBO фенове" onPress={()=>openPage('CIBO KIDS',SITE)}/><QuickCard emoji="🎁" title="Изпрати CIBO" subtitle="Подарък и CIBO изненада" onPress={()=>openPage('Изпрати CIBO',SITE)}/><View style={styles.infoBox}><Text style={styles.infoTitle}>📍 Получаване на място</Text><Text style={styles.infoText}>Паркингът зад Еконт, Златоград</Text><Text style={styles.infoText}>Телефон: 0879 199 799</Text></View><Pressable style={styles.pushBtn} onPress={enablePush}><Text style={styles.pushText}>🔔 Разреши известия от CIBO</Text></Pressable><Text style={styles.footer}>MORE THAN FOOD. IT'S A FEELING.</Text></ScrollView></SafeAreaView>
}

function BrowserScreen({title,url,onClose}){
 const web=useRef(null);const[loading,setLoading]=useState(true);const[canBack,setCanBack]=useState(false);
 const shouldStart=(request)=>{const u=request.url||'';const external=u.includes('epg.dskbank.bg')||u.includes('dskbank.bg/payment')||u.startsWith('tel:')||u.startsWith('mailto:');if(external){if(u.startsWith('tel:')||u.startsWith('mailto:'))Linking.openURL(u);else WebBrowser.openBrowserAsync(u);return false}return true};
 return <SafeAreaView style={styles.browserSafe}><View style={styles.browserBar}><Pressable onPress={onClose} style={styles.browserBtn}><Text style={styles.browserBtnText}>✕</Text></Pressable><Text numberOfLines={1} style={styles.browserTitle}>{title}</Text><Pressable onPress={()=>web.current?.reload()} style={styles.browserBtn}><Text style={styles.browserBtnText}>↻</Text></Pressable></View>{loading&&<View style={styles.loader}><ActivityIndicator size="large"/><Text style={styles.loaderText}>Зареждам CIBO…</Text></View>}<WebView ref={web} source={{uri:url}} onLoadStart={()=>setLoading(true)} onLoadEnd={()=>setLoading(false)} onNavigationStateChange={s=>setCanBack(s.canGoBack)} onShouldStartLoadWithRequest={shouldStart} javaScriptEnabled domStorageEnabled sharedCookiesEnabled thirdPartyCookiesEnabled pullToRefreshEnabled allowsBackForwardNavigationGestures setSupportMultipleWindows={false} style={{flex:1,opacity:loading?0:1}}/><View style={styles.browserBottom}><Pressable disabled={!canBack} onPress={()=>web.current?.goBack()} style={[styles.navBtn,!canBack&&styles.navDisabled]}><Text style={styles.navText}>‹ Назад</Text></Pressable><Pressable onPress={()=>Linking.openURL(url)} style={styles.navBtn}><Text style={styles.navText}>Отвори в браузър ↗</Text></Pressable></View></SafeAreaView>
}

export default function App(){const[page,setPage]=useState(null);useEffect(()=>{if(Platform.OS==='android')Notifications.setNotificationChannelAsync('orders',{name:'Поръчки',importance:Notifications.AndroidImportance.HIGH,vibrationPattern:[0,250,200,250]}).catch(()=>{})},[]);const openPage=async(title,url)=>{await Haptics.selectionAsync().catch(()=>{});setPage({title,url})};if(page)return <BrowserScreen title={page.title} url={page.url} onClose={()=>setPage(null)}/>;return <><StatusBar barStyle="dark-content" backgroundColor={C.cream}/><Home openPage={openPage}/></>}

const styles=StyleSheet.create({safe:{flex:1,backgroundColor:C.cream},home:{padding:20,paddingBottom:42},brandWrap:{alignItems:'center',marginTop:6,marginBottom:20},oven:{width:58,height:42,borderTopLeftRadius:30,borderTopRightRadius:30,backgroundColor:C.green,alignItems:'center',justifyContent:'center',borderWidth:3,borderColor:C.gold},flame:{fontSize:22},brand:{fontSize:29,fontWeight:'900',letterSpacing:1.2,color:C.ink,marginTop:7},subbrand:{fontSize:11,letterSpacing:3,color:C.gold,fontWeight:'700',marginTop:2},hero:{backgroundColor:C.green,borderRadius:28,padding:24,marginBottom:26},kicker:{fontSize:11,fontWeight:'900',letterSpacing:1.5,color:'#E9C479',marginBottom:11},heroTitle:{fontSize:36,lineHeight:39,fontWeight:'900',color:'#FFFDF7',letterSpacing:-1},heroText:{fontSize:15,lineHeight:22,color:'#E8E5DC',marginTop:13,marginBottom:20},primary:{backgroundColor:C.orange,borderRadius:16,paddingVertical:17,alignItems:'center'},primaryText:{color:'white',fontWeight:'900',fontSize:17,letterSpacing:.7},sectionTitle:{fontSize:13,fontWeight:'900',letterSpacing:1.6,color:C.muted,marginBottom:10},quickCard:{backgroundColor:C.paper,borderWidth:1.5,borderRadius:20,padding:16,marginBottom:11,flexDirection:'row',alignItems:'center'},quickEmoji:{fontSize:28,width:44},quickTitle:{fontSize:18,fontWeight:'900',color:C.ink},quickSub:{fontSize:13,color:C.muted,marginTop:3,lineHeight:18},chev:{fontSize:32,color:C.gold,marginLeft:8},infoBox:{marginTop:10,backgroundColor:C.soft,borderRadius:18,padding:18},infoTitle:{fontSize:16,fontWeight:'900',color:C.ink},infoText:{fontSize:14,color:C.muted,marginTop:6},pushBtn:{marginTop:13,borderRadius:16,borderWidth:1.3,borderColor:C.green2,padding:15,alignItems:'center'},pushText:{fontWeight:'800',color:C.green2},footer:{textAlign:'center',fontSize:11,letterSpacing:2,color:C.gold,fontWeight:'900',marginTop:28},browserSafe:{flex:1,backgroundColor:C.paper,paddingTop:Platform.OS==='android'?StatusBar.currentHeight||0:0},browserBar:{height:54,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:C.border,paddingHorizontal:8,backgroundColor:C.paper},browserBtn:{width:44,height:44,alignItems:'center',justifyContent:'center'},browserBtnText:{fontSize:22,color:C.green,fontWeight:'800'},browserTitle:{flex:1,textAlign:'center',fontWeight:'900',color:C.ink,fontSize:16},loader:{...StyleSheet.absoluteFillObject,top:54,alignItems:'center',justifyContent:'center',backgroundColor:C.cream,zIndex:3},loaderText:{marginTop:10,color:C.muted,fontWeight:'700'},browserBottom:{height:50,borderTopWidth:1,borderTopColor:C.border,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:8,backgroundColor:C.paper},navBtn:{paddingHorizontal:12,paddingVertical:10},navDisabled:{opacity:.3},navText:{fontWeight:'800',color:C.green}});
